name: Build and Release Dify Package

on:
  release:
    types: [published]

jobs:
  package-and-release:
    defaults:
      run:
        working-directory: ./
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'arm64_runner' || 'ubuntu-latest' }}
    if: github.repository == 'chekun/dify-plugin-shopify'
    strategy:
      matrix:
        include:
          - platform: linux/amd64

    steps:
    - name: Download dify
      run: |
        curl -L -o dify "https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.4/dify-plugin-linux-amd64"
        chmod +x dify

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: shopify

    - name: Package plugin
      run: |
        ./dify plugin package shopify
        mv shopify.difypkg shopify.${{ github.event.release.tag_name }}.difypkg

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: $(file -b --mime-type shopify.${{ github.event.release.tag_name }}.difypkg)" \
          --data-binary "@shopify.${{ github.event.release.tag_name }}.difypkg" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=$(basename shopify.${{ github.event.release.tag_name }}.difypkg)"