name: Build and Release Dify Package

on:
  release:
    types: [published]

jobs:
  package-and-release:
    defaults:
      run:
        working-directory: ./app
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'arm64_runner' || 'ubuntu-latest' }}
    if: github.repository == 'chekun/dify-plugin-shopify'
    strategy:
      matrix:
        include:
          - platform: linux/amd64

    steps:
    - name: Download dify
      run: |
        curl -L -o dify "https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.4/dify-plugin-linux-${{ matrix.platform }}"
        chmod +x dify

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: shopify

    - name: Package plugin
      run: |
        ./dify plugin package shopify
        mv shopify.difypkg shopify.${{ github.event.release.tag_name }}.difypkg

    - name: Upload Release Asset
      run: |
        gh release upload ${{ github.event.release.tag_name }} shopify.${{ github.event.release.tag_name }}.difypkg --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}